baseurl: 
title: Tufte
subtitle: Content-centric blogging
author: clay harmon
simple_search: http://google.com/search
description: A Jekyll theme for content-rich sites
name: tufte
markdown: kramdown
kramdown:  
  input: GFM
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
#highlighter: rouge
permalink: /:short_year/:title
timezone: Asia/Shanghai
#excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: vim
git:
  branch: master
